# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7024afc1ad0cc6dc6351c1d57fcb46853dd1a1da0633d83fd7e0d37717ded2d8901c948fa2256c3a8c9df0d03c090fdfabde616ea3dceb4622bb2afd517a14a0

test:
  secret_key_base: 1382fa1ca7fb9f178d21e9fcd04c8c3a4f94fca73c5ff1fd1d04a18c83085eb1f15d38ff9b12f517b1d23040a254ac830e6262ef37f511079fa4160ecda1b27c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
